# Generated by Django 6.0.3 on 2026-03-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateTimeField()),
                ('couisine', models.CharField(choices=[('italy', 'ITALY'), ('french', 'French'), ('ukraine', 'Ukraine')], default='ukraine', max_length=20)),
            ],
            options={
                'db_table': 'menu',
                'managed': False,
            },
        ),
    ]
